In [1]:
import pandas as pd
import numpy as np

### Steps for the Project

#### 1. Read the data
#### 2. Data preprocessing/Cleaning if value is missing(NaN) 
#### y = (mx1+mx2+mx3)+b

In [2]:
df = pd.read_csv('homeprices(1).csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
median_bedrooms = df.bedrooms.median()

In [9]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg = LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [13]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
reg.intercept_

221323.00186540384

In [19]:
predict_value = [[3000,3,40]]
predict_value1 = [[2500,4,5]]

reg.predict(predict_value1)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

## Exercise

In [20]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [21]:
df['test_score(out of 10)'].isnull().sum()

1

In [23]:
median_score = df['test_score(out of 10)'].median()

In [25]:
df['test_score(out of 10)'].fillna(median_score,inplace=True)

In [27]:
df.experience.isnull().sum()

2

In [31]:
df.experience.fillna('zero',inplace=True)

In [32]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [40]:
from word2number import w2n

df.experience = df.experience.apply(lambda x: w2n.word_to_num(x))

In [41]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [42]:
from sklearn.linear_model import LinearRegression

lin_reg_mul = LinearRegression()

In [43]:
lin_reg_mul.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])


LinearRegression()

In [45]:
predict_value = [[2,9,6]]
predict_value1 = [[12,10,10]]

lin_reg_mul.predict(predict_value),lin_reg_mul.predict(predict_value1)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


(array([53205.96797671]), array([92002.18340611]))